-- Create predefined_tasks table
CREATE TABLE IF NOT EXISTS public.predefined_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT unique_task_per_dept UNIQUE (task_name, department)
);

-- Enable RLS
ALTER TABLE public.predefined_tasks ENABLE ROW LEVEL SECURITY;

-- Allow select to all authenticated users
CREATE POLICY "Allow authenticated users to read predefined tasks" ON public.predefined_tasks
  FOR SELECT TO authenticated USING (true);

-- Allow HODs of matching department to manage tasks
CREATE POLICY "Allow HODs to insert predefined tasks for their department" ON public.predefined_tasks
  FOR INSERT TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
      AND profiles.department = predefined_tasks.department
    )
  );

CREATE POLICY "Allow HODs to update predefined tasks for their department" ON public.predefined_tasks
  FOR UPDATE TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
      AND profiles.department = predefined_tasks.department
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
      AND profiles.department = predefined_tasks.department
    )
  );

CREATE POLICY "Allow HODs to delete predefined tasks for their department" ON public.predefined_tasks
  FOR DELETE TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
      AND profiles.department = predefined_tasks.department
    )
  );

-- Seed predefined tasks for Fabrication
INSERT INTO public.predefined_tasks (task_name, department) VALUES
  ('Coil Loading', 'Fabrication'),
  ('Shearing & Slitting', 'Fabrication'),
  ('Tack Welding', 'Fabrication'),
  ('Final Welding Inspection', 'Fabrication'),
  ('Grinding & Buffing', 'Fabrication'),
  ('Laser Cutting Prep', 'Fabrication')
ON CONFLICT (task_name, department) DO NOTHING;
