-- Create project_components table
CREATE TABLE IF NOT EXISTS public.project_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL,
  component_name TEXT NOT NULL,
  drawing_no TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT unique_component_per_project UNIQUE (project_id, component_name)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.project_components ENABLE ROW LEVEL SECURITY;

-- Allow SELECT access to all authenticated users
CREATE POLICY "Allow authenticated users to read project components" ON public.project_components
  FOR SELECT TO authenticated USING (true);

-- Allow HODs to manage components
CREATE POLICY "Allow HODs to manage project components" ON public.project_components
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );

-- Create index on project_id for fast retrieval
CREATE INDEX IF NOT EXISTS idx_project_components_project_id ON public.project_components(project_id);
