-- Create fabrication_rods table
CREATE TABLE IF NOT EXISTS public.fabrication_rods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rod_type TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.fabrication_rods ENABLE ROW LEVEL SECURITY;

-- Allow SELECT access to all authenticated users
CREATE POLICY "Allow authenticated users to read fabrication rods" ON public.fabrication_rods
  FOR SELECT TO authenticated USING (true);

-- Allow HODs to manage rods
CREATE POLICY "Allow HODs to manage fabrication rods" ON public.fabrication_rods
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );
