-- Create project_coils table
CREATE TABLE IF NOT EXISTS public.project_coils (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL,
  coil_no TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT unique_coil_per_project UNIQUE (project_id, coil_no)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.project_coils ENABLE ROW LEVEL SECURITY;

-- Allow SELECT access to all authenticated users
CREATE POLICY "Allow authenticated users to read project coils" ON public.project_coils
  FOR SELECT TO authenticated USING (true);

-- Allow HODs to manage coils
CREATE POLICY "Allow HODs to manage project coils" ON public.project_coils
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );

-- Create index on project_id for fast retrieval
CREATE INDEX IF NOT EXISTS idx_project_coils_project_id ON public.project_coils(project_id);
