-- Create fabrication_coils table
CREATE TABLE IF NOT EXISTS public.fabrication_coils (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coil_no TEXT NOT NULL UNIQUE,
  received_date DATE,
  status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.fabrication_coils ENABLE ROW LEVEL SECURITY;

-- Allow SELECT access to all authenticated users
CREATE POLICY "Allow authenticated users to read fabrication coils" ON public.fabrication_coils
  FOR SELECT TO authenticated USING (true);

-- Allow HODs to manage coils
CREATE POLICY "Allow HODs to manage fabrication coils" ON public.fabrication_coils
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );
