-- Create project_rods table
CREATE TABLE IF NOT EXISTS public.project_rods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL,
  rod_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT unique_rod_per_project UNIQUE (project_id, rod_type)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.project_rods ENABLE ROW LEVEL SECURITY;

-- Allow SELECT access to all authenticated users
CREATE POLICY "Allow authenticated users to read project rods" ON public.project_rods
  FOR SELECT TO authenticated USING (true);

-- Allow HODs to manage rods
CREATE POLICY "Allow HODs to manage project rods" ON public.project_rods
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );

-- Create index on project_id for fast retrieval
CREATE INDEX IF NOT EXISTS idx_project_rods_project_id ON public.project_rods(project_id);
